In [1]:
import numpy as np

In [2]:
a = np.arange(10,100,10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
index = [[0,3,8]]
a[index]

array([[10, 40, 90]])

In [13]:
index = np.arange(0,9,3)
a[[index]]

array([[10, 40, 70]])

In [14]:
# 2D Array

In [15]:
a.shape = (3,3)
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
a[(0,1),(0,2)]

array([10, 60])

In [38]:
a[(0,1,2),(0,2,0)]

array([10, 60, 70])

In [39]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
a[(0,1,1,2),(1,0,2,1)]

array([20, 40, 60, 80])

In [41]:
# 3D Array

In [47]:
a = np.arange(10,190,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180])

In [48]:
a.shape = (3,2,3)
a

array([[[ 10,  20,  30],
        [ 40,  50,  60]],

       [[ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180]]])

In [51]:
a[(0,1,2),(0,0,0),(0,0,0)]

array([ 10,  70, 130])

In [54]:
a[(0,0,1,1,2,2),(0,1,0,1,0,1),(0,2,0,2,0,2)]

array([ 10,  60,  70, 120, 130, 180])