In [7]:
import numpy as np

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
a = np.append(a,12)

In [10]:
a = np.append(a,[13,14,15])     # add multiple value

In [11]:
a = np.insert(a,2,16)           #insert any specific location

In [12]:
a

array([ 1,  2, 16,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
a = np.insert(a,5,[17,18,19,20,21])

In [14]:
a

array([ 1,  2, 16,  3,  4, 17, 18, 19, 20, 21,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15])

In [16]:
a = np.delete(a,9)

In [17]:
a

array([ 1,  2, 16,  3,  4, 17, 18, 19, 20,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15])

In [20]:
a= np.delete(a,np.s_[5:9])
a

array([ 1,  2, 16,  3,  4,  8,  9, 10, 11, 12, 13, 14, 15])