In [1]:
import numpy as np

In [5]:
a = np.arange(15,-12,-3)
a

array([15, 12,  9,  6,  3,  0, -3, -6, -9])

In [19]:
# preparing boolean array with condition  --- ndarray wit conditon
ba =(a%2==0)
ba

array([False,  True, False,  True, False,  True, False,  True, False])

In [22]:
# Direct Purpose 
# syntax = ndarryobj[ndarrayobj with condition]

In [20]:
a[a>0]

array([15, 12,  9,  6,  3])

In [21]:
a[a%2==0]

array([12,  6,  0, -6])

In [25]:
a

array([15, 12,  9,  6,  3,  0, -3, -6, -9])

In [30]:
a[a%2==0]

array([12,  6,  0, -6])

In [38]:
a[(a%2==0) & (a>=0)]

array([12,  6,  0])