In [1]:
import numpy as np

In [2]:
x = 10
a = np.array(x)
print(a,type(a))

10 <class 'numpy.ndarray'>


In [3]:
a

array(10)

In [4]:
a.ndim

0

In [5]:
a.shape

()

In [6]:
x = [10]
a = np.array(x)
print(a,type(a))


[10] <class 'numpy.ndarray'>


In [7]:
a

array([10])

In [8]:
a.shape

(1,)

In [9]:
r = range(10,25)
a = np.array(r)
print(a,type(a),len(a))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] <class 'numpy.ndarray'> 15


In [10]:
a.ndim

1

In [11]:
a.shape

(15,)

In [12]:
a.shape = (3,5)
print(a)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [13]:
a.ndim

2

In [14]:
r = range(10,25)
a = np.array(r,dtype=float)
print(a,type(a))

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24.] <class 'numpy.ndarray'>


In [15]:
a.dtype

dtype('float64')

In [16]:
r = range(10,25)
a = np.array(r)
print(a,type(a))
a.dtype

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] <class 'numpy.ndarray'>


dtype('int32')

In [17]:
lst = [10,20,30,40,50,60]
print(lst,type(lst))
a = np.array(lst)
print(a,type(a),len(a))

[10, 20, 30, 40, 50, 60] <class 'list'>
[10 20 30 40 50 60] <class 'numpy.ndarray'> 6


In [18]:
print(a.ndim)
print(a.shape)
print(a.dtype)

1
(6,)
int32


In [19]:
a.shape = (2,3)
a

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
print(a.ndim)
print(a.shape)
print(a.dtype)

2
(2, 3)
int32


In [21]:
tpl = (10,20,30,40,50,60)
print(tpl,type(tpl))
a = np.array(tpl)
a.shape = (2,3)
print(a,type(a),len(a))

(10, 20, 30, 40, 50, 60) <class 'tuple'>
[[10 20 30]
 [40 50 60]] <class 'numpy.ndarray'> 2


In [22]:
print(a.ndim)
print(a.shape)
print(a.dtype)

2
(2, 3)
int32


In [23]:
s = {10,20,30,40,50,60}
print(lst,type(s))
a = np.array(s)
print(a,type(a))

[10, 20, 30, 40, 50, 60] <class 'set'>
{50, 20, 40, 10, 60, 30} <class 'numpy.ndarray'>


In [24]:
print(a.ndim)
print(a.shape)
print(a.dtype)

0
()
object


In [25]:
d1 = {10:"Apple",20:"Banana",30:"Kiwi",40:"Mango"}
print(d1,type(d1))
a = np.array(d1)
print(a,type(a))

{10: 'Apple', 20: 'Banana', 30: 'Kiwi', 40: 'Mango'} <class 'dict'>
{10: 'Apple', 20: 'Banana', 30: 'Kiwi', 40: 'Mango'} <class 'numpy.ndarray'>


In [26]:
print(a.ndim)
print(a.shape)
print(a.dtype)

0
()
object


In [27]:
a

array({10: 'Apple', 20: 'Banana', 30: 'Kiwi', 40: 'Mango'}, dtype=object)

In [28]:
# Function Name---arange()
# Syntax = numpy.arange(values)              0 to value-1
# Syntax = numpy.arange(begin,end)           begin to end-1
# Syntax = numpy.arange(begin,end,step)      begin to end-1 with step

In [30]:
a = np.arange(10)
print(a,type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
1
(10,)
int32


In [35]:
a = np.arange(1,26)
print(a,type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25] <class 'numpy.ndarray'>
1
(25,)
int32


In [37]:
a.shape = (5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [45]:
a = np.arange(10,51,5)
print(a,type(a))
print(a.ndim)
print(a.shape)
print(a.dtype)

[10 15 20 25 30 35 40 45 50] <class 'numpy.ndarray'>
1
(9,)
int32


In [46]:
a.shape = (3,3)
print(a)

[[10 15 20]
 [25 30 35]
 [40 45 50]]


In [47]:
# Function name: zeros()
# Syntax: varname = numpy.zeros(shape,dtype)

In [54]:
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [55]:
a = np.zeros(6,dtype=int)
a

array([0, 0, 0, 0, 0, 0])

In [58]:
a = np.zeros((3,3),int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
# Function name: ones()
# Syntax: varname = numpy.ones(shape,dtype)

In [60]:
a = np.ones(6)
a

array([1., 1., 1., 1., 1., 1.])

In [68]:
a = np.zeros((3,3),dtype=[('x','f2'),('y','i4')])       # custome type
a

array([[(0., 0), (0., 0), (0., 0)],
       [(0., 0), (0., 0), (0., 0)],
       [(0., 0), (0., 0), (0., 0)]], dtype=[('x', '<f2'), ('y', '<i4')])

In [72]:
# Function name: full()
# Syntax: varname = numpy.full(shape,dtype)

In [73]:
a = np.full((3,3),fill_value=2)
a

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [79]:
a = np.full((3,3),fill_value="dinesh")
a

array([['dinesh', 'dinesh', 'dinesh'],
       ['dinesh', 'dinesh', 'dinesh'],
       ['dinesh', 'dinesh', 'dinesh']], dtype='<U6')

In [80]:
# Function name: identity()
# Syntax: varname = numpy.identity(N,dtype)

In [86]:
a = np.identity(5,int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [88]:
# Function name: hstack()
# Syntax: varname = numpy.hstack(ndarrayobj1,ndarrayobj2)

In [94]:
a = np.arange(10,21)
b = np.arange(20,31)
c = np.hstack((a,b))
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30])

In [95]:
# Function name: vstack()
# Syntax: varname = numpy.vstack(ndarrayobj1,ndarrayobj2)

In [99]:
a = np.array([10,11,12,13,14])
b = np.array([20,21,22,23,24])
c = np.vstack((a,b))
c

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [101]:
a = np.arange(10,21)
b = np.arange(20,31)
c = np.vstack((a,b))
c

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])