In [1]:
import numpy as np

In [18]:
a = np.arange(10,45,4)
a.shape = (3,3)
a

array([[10, 14, 18],
       [22, 26, 30],
       [34, 38, 42]])

In [22]:
a[:3:2,:3:2]

array([[10, 18],
       [34, 42]])

In [23]:
a[::2,::2]

array([[10, 18],
       [34, 42]])

In [24]:
# 3d Array

In [34]:
a = np.arange(10,80,4)
a.shape = (3,2,3)
a

array([[[10, 14, 18],
        [22, 26, 30]],

       [[34, 38, 42],
        [46, 50, 54]],

       [[58, 62, 66],
        [70, 74, 78]]])

In [38]:
a[0:3,0:1,0:3]

array([[[10, 14, 18]],

       [[34, 38, 42]],

       [[58, 62, 66]]])

In [45]:
a[0:3,0:3,1:3]

array([[[14, 18],
        [26, 30]],

       [[38, 42],
        [50, 54]],

       [[62, 66],
        [74, 78]]])

In [46]:
a[:,:,1:3]

array([[[14, 18],
        [26, 30]],

       [[38, 42],
        [50, 54]],

       [[62, 66],
        [74, 78]]])

In [49]:
a[:,0:1,::3]

array([[[10]],

       [[34]],

       [[58]]])

In [50]:
print(a)

[[[10 14 18]
  [22 26 30]]

 [[34 38 42]
  [46 50 54]]

 [[58 62 66]
  [70 74 78]]]


In [54]:
a[:,1:2,::3]

array([[[22]],

       [[46]],

       [[70]]])

In [57]:
a[:,1:,::2]

array([[[22, 30]],

       [[46, 54]],

       [[70, 78]]])

In [63]:
a[::,1:,1::2]

array([[[26]],

       [[50]],

       [[74]]])