In [1]:
# let us consider 3x+2y=12
#                 2x-y =1       find x,y
# Methods 1

In [2]:
import numpy as np

In [3]:
a = np.array([[3,2],[2,-1]])
b = np.array([12,1])

In [4]:
x = np.linalg.solve(a,b)
x

array([2., 3.])

In [5]:
# let us consider 3x+2y=12
#                 2x-y =1       find x,y
# Methods 1

In [6]:
a = np.array([[3,2],[2,-1]])
b = np.array([12,1])

In [9]:
ai = np.linalg.inv(a)
ai

array([[ 0.14285714,  0.28571429],
       [ 0.28571429, -0.42857143]])

In [12]:
x = np.matmul(ai,b)
x

array([2., 3.])

In [13]:
x = np.dot(ai,b)
x

array([2., 3.])