In [1]:
import numpy as np

In [3]:
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[[10 20]
 [30 40]]
[[1 2]
 [3 4]]


In [4]:
c = np.add(a,b)

In [5]:
print(c)

[[11 22]
 [33 44]]


In [6]:
d = a+b
print(d)

[[11 22]
 [33 44]]


In [7]:
c = np.subtract(a,b)
print(c)
d = a-b
print(d)

[[ 9 18]
 [27 36]]
[[ 9 18]
 [27 36]]


In [8]:
#element wise matrix multiplication
c = np.multiply(a,b)
print(c)
d = a*b
print(d)

[[ 10  40]
 [ 90 160]]
[[ 10  40]
 [ 90 160]]


In [9]:
# Original matrix multiplication
c = np.dot(a,b)
print(c)

[[ 70 100]
 [150 220]]


In [10]:
c = np.divide(a,b)
print(c)
d = a/b
print(d)

[[10. 10.]
 [10. 10.]]
[[10. 10.]
 [10. 10.]]


In [11]:
c = np.floor_divide(a,b)
print(c)
d = a//b
print(d)

[[10 10]
 [10 10]]
[[10 10]
 [10 10]]


In [12]:
c = np.power(a,b)
print(c)
d = a**b
print(d)

[[     10     400]
 [  27000 2560000]]
[[     10     400]
 [  27000 2560000]]
