In [3]:
import numpy as np
a = np.array([[10,15,25],[35, 24,12],[36,28,19]])
print(a)
a.shape = (9,)
a

[[10 15 25]
 [35 24 12]
 [36 28 19]]


array([10, 15, 25, 35, 24, 12, 36, 28, 19])

In [4]:
np.sort(a)

array([10, 12, 15, 19, 24, 25, 28, 35, 36])

In [5]:
a = np.array([[10,15,25],[35, 24,12],[36,28,19]])
a

array([[10, 15, 25],
       [35, 24, 12],
       [36, 28, 19]])

In [6]:
np.sort(a) # row wise sort

array([[10, 15, 25],
       [12, 24, 35],
       [19, 28, 36]])

In [9]:
np.sort(a, axis = 0) # col wise sort

array([[10, 15, 12],
       [35, 24, 19],
       [36, 28, 25]])

In [10]:
a = np.array([[[1, 2, 3, 4, 5],
                   [1, 2, 2, 2, 2]],
                   [[4, 5, 7, 9, 4],
                   [6, 7, 8, 9, 2]],
                   [[2, 3, 4, 8, 6],
                    [1, 2, 2, 2, 2]]])

In [11]:
a

array([[[1, 2, 3, 4, 5],
        [1, 2, 2, 2, 2]],

       [[4, 5, 7, 9, 4],
        [6, 7, 8, 9, 2]],

       [[2, 3, 4, 8, 6],
        [1, 2, 2, 2, 2]]])

In [12]:
np.sort(a) # Row wise sort

array([[[1, 2, 3, 4, 5],
        [1, 2, 2, 2, 2]],

       [[4, 4, 5, 7, 9],
        [2, 6, 7, 8, 9]],

       [[2, 3, 4, 6, 8],
        [1, 2, 2, 2, 2]]])

In [13]:
np.sort(a,axis=0) # col wise sot

array([[[1, 2, 3, 4, 4],
        [1, 2, 2, 2, 2]],

       [[2, 3, 4, 8, 5],
        [1, 2, 2, 2, 2]],

       [[4, 5, 7, 9, 6],
        [6, 7, 8, 9, 2]]])