In [1]:
import numpy as np

In [2]:
a = np.array([[10,15,25],[35, 24,12],[36,28,19]])
a

array([[10, 15, 25],
       [35, 24, 12],
       [36, 28, 19]])

In [3]:
maxv = np.amax(a)
maxv

36

In [5]:
colmax = np.amax(a,axis = 0)
rowmax = np.amax(a,axis = 1)
print(colmax)
print(rowmax)

[36 28 25]
[25 35 36]


In [7]:
minv = np.amin(a)
print(minv)
colmax = np.amin(a,axis = 0)
rowmax = np.amin(a,axis = 1)
print(colmax)
print(rowmax)

10
[10 15 12]
[10 12 19]


In [9]:
meanv = np.mean(a)

print(meanv)

22.666666666666668


In [10]:
colmean = np.mean(a, axis=0)
rowmean = np.mean(a, axis=1)
print(colmean)
print(rowmean)

[27.         22.33333333 18.66666667]
[16.66666667 23.66666667 27.66666667]


In [11]:
med = np.median(a)
print(med)

24.0


In [12]:
colmed = np.median(a, axis=0)
rowmed = np.median(a, axis=1)
print(colmed)
print(rowmed)

[35. 24. 19.]
[15. 24. 28.]


In [14]:
var = np.var(a)
print(var)
colvar = np.var(a, axis=0)
rowvar = np.var(a, axis=1)
print(colvar)
print(rowvar)

79.11111111111111
[144.66666667  29.55555556  28.22222222]
[38.88888889 88.22222222 48.22222222]


In [15]:
s = np.std(a)
print(s)
colstd = np.std(a, axis=0)
rowstd = np.std(a, axis=1)
print(colstd)
print(rowstd)

8.894442709417556
[12.0277457   5.43650214  5.31245915]
[6.23609564 9.39266854 6.94422222]


In [16]:
import statistics as s

In [23]:
lst = [1, 2, 3, 4, 5,1, 2, 2, 2, 2,4, 5, 7, 9, 4,6, 7, 8, 9, 2,2, 3, 4, 8, 6]
lst

[1, 2, 3, 4, 5, 1, 2, 2, 2, 2, 4, 5, 7, 9, 4, 6, 7, 8, 9, 2, 2, 3, 4, 8, 6]

In [25]:
freq = s.mode(lst)
freq

2

In [26]:
mmode = s.multimode(lst)
mmode

[2]